#!/bin/bash
set -eu

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

ynh_restore_file --origin_path="$data_dir"
ynh_restore_file --origin_path="$install_dir"
chown -R "$app:$app" "$data_dir" "$install_dir"
configure_files
yunohost service add "$app" --description="Création de plans de contrôle gammagraphique" --log="systemd" || true
ynh_systemctl --service="$app" --action="start" --log_path="systemd"
ynh_systemctl --service="nginx" --action="reload"
